type Session={token:string;user?:{role?:string}};
type LocationItem={id:number;category:string;place_type:string;name:string;km:string;waze_url:string;maps_url:string;coordinates:string;notes:string};

const API=(import.meta.env.VITE_API_URL||'/api').replace(/\/$/,'');
const MARKER='[תחנת נוסעים רכבת ישראל]';
const STATIONS=[
'דימונה','באר שבע מרכז','באר שבע צפון – אוניברסיטה','להבים – רהט','קריית גת','אופקים','נתיבות','שדרות','אשקלון','קריית מלאכי – יואב','אשדוד – עד הלום','יבנה מערב','יבנה מזרח','רחובות','מזכרת בתיה','רמלה','לוד','לוד – גני אביב','באר יעקב','ראשון לציון – הראשונים','ראשון לציון – משה דיין','בת ים – קוממיות','בת ים – יוספטל','צומת חולון','חולון – וולפסון','כפר חב״ד','נתב״ג','בית שמש','ירושלים – יצחק נבון','ירושלים – גן החיות התנ״כי','ירושלים – מלחה','מודיעין מרכז','פאתי מודיעין','תל אביב – ההגנה','תל אביב – השלום','תל אביב – סבידור מרכז','תל אביב – אוניברסיטה','בני ברק','פתח תקווה – קריית אריה','פתח תקווה – סגולה','ראש העין צפון','כפר סבא – נורדאו','הוד השרון – סוקולוב','רעננה דרום','רעננה מערב','הרצליה','בית יהושע','נתניה – ספיר','נתניה','חדרה מערב','קיסריה – פרדס חנה','בנימינה','עתלית','חיפה – חוף הכרמל','חיפה – בת גלים','חיפה מרכז – השמונה','מרכזית המפרץ','חוצות המפרץ','קריית חיים','קריית מוצקין','עכו','אחיהוד','כרמיאל','יקנעם – כפר יהושע','מגדל העמק – כפר ברוך','עפולה','בית שאן','נהריה'
] as const;

function getSession():Session|null{try{return JSON.parse(localStorage.getItem('danel_location_session')||sessionStorage.getItem('danel_location_session')||'null')}catch{return null}}
async function api<T>(path:string,options:RequestInit={}):Promise<T>{const s=getSession();if(!s?.token)throw new Error('נדרשת התחברות');const response=await fetch(`${API}${path}`,{...options,headers:{'Content-Type':'application/json',Authorization:`Bearer ${s.token}`,...(options.headers||{})}});if(!response.ok){let detail:any='שגיאה בשמירת התחנה';try{const body=await response.json();detail=body.detail||detail}catch{}throw new Error(typeof detail==='string'?detail:detail.message||'שגיאה בשמירת התחנה')}return response.status===204?undefined as T:response.json()}
const normalize=(value:string)=>value.replace(/[״׳'"\-–—\s]/g,'').toLowerCase();
const mapsUrl=(lat:number,lng:number)=>`https://www.google.com/maps/search/?api=1&query=${lat},${lng}`;
const wazeUrl=(lat:number,lng:number)=>`https://www.waze.com/ul?ll=${lat},${lng}&navigate=yes`;
const sleep=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms));
function escapeHtml(value:string){const table:Record<string,string>={'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'};return value.replace(/[&<>'"]/g,char=>table[char])}

async function geocode(name:string){const query=encodeURIComponent(`תחנת רכבת ${name}, ישראל`);const response=await fetch(`https://nominatim.openstreetmap.org/search?format=json&limit=1&countrycodes=il&q=${query}`,{headers:{'Accept-Language':'he'}});if(!response.ok)return null;const rows=await response.json();if(!rows?.[0])return null;const lat=Number(rows[0].lat),lng=Number(rows[0].lon);return Number.isFinite(lat)&&Number.isFinite(lng)?{lat,lng}:null}

let seedStarted=false;
async function seedStations(){const current=getSession();if(seedStarted||current?.user?.role!=='owner')return;seedStarted=true;try{const all=await api<LocationItem[]>('/locations');const existing=new Set(all.filter(item=>item.notes.includes(MARKER)).map(item=>normalize(item.name)));const missing=STATIONS.filter(name=>!existing.has(normalize(name)));for(const name of missing){try{const point=await geocode(name);if(point){await api('/locations',{method:'POST',body:JSON.stringify({category:'reporting_point',place_type:'station',name,km:'',coordinates:`${point.lat.toFixed(6)}, ${point.lng.toFixed(6)}`,maps_url:mapsUrl(point.lat,point.lng),waze_url:wazeUrl(point.lat,point.lng),notes:MARKER,allow_duplicate:false})})}}catch(error){console.warn('Passenger station seed failed',name,error)}await sleep(1100)}}finally{seedStarted=false}}

function ensureStyles(){if(document.getElementById('passenger-stations-style'))return;const style=document.createElement('style');style.id='passenger-stations-style';style.textContent=`.ps-view{padding:22px}.ps-head{display:flex;justify-content:space-between;align-items:center;gap:18px;margin-bottom:20px}.ps-head h2{margin:0 0 5px}.ps-head p{margin:0;color:#6b7280}.ps-search{min-width:240px;border:1px solid #ccd6e5;border-radius:10px;padding:12px}.ps-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(280px,1fr));gap:14px}.ps-card{border:1px solid #dde5ef;border-radius:14px;padding:18px;background:#fff;display:flex;justify-content:space-between;gap:16px}.ps-card h3{margin:8px 0}.ps-card small{color:#6b7280}.ps-badge{font-size:12px;font-weight:800;color:#1746b8;background:#eaf0ff;padding:4px 8px;border-radius:999px}.ps-links{display:flex;flex-direction:column;gap:7px;min-width:105px}.ps-links a,.ps-links button{border:0;border-radius:8px;padding:8px 10px;text-align:center;text-decoration:none;background:#eef3ff;color:#1746b8;font-weight:700;cursor:pointer}.ps-modal{position:fixed;inset:0;background:#0008;z-index:9999;display:grid;place-items:center;padding:18px}.ps-dialog{width:min(620px,100%);max-height:90vh;overflow:auto;background:#fff;border-radius:18px;padding:24px;position:relative}.ps-dialog h2{margin-top:0}.ps-dialog label{display:grid;gap:6px;margin:12px 0;font-weight:700}.ps-dialog input,.ps-dialog textarea{border:1px solid #ccd6e5;border-radius:9px;padding:11px}.ps-dialog textarea{min-height:90px}.ps-close{position:absolute;left:16px;top:12px;border:0;background:none;font-size:28px}.ps-actions{display:flex;justify-content:flex-end;gap:10px;margin-top:18px}.ps-actions button{padding:10px 18px;border-radius:9px;border:0;font-weight:800}.ps-save{background:#1746b8;color:#fff}.ps-error{color:#b42318}.ps-loading{padding:32px;text-align:center}@media(max-width:650px){.ps-head{align-items:stretch;flex-direction:column}.ps-search{min-width:0}.ps-card{flex-direction:column}.ps-links{flex-direction:row;flex-wrap:wrap}}`;document.head.appendChild(style)}

function openEditor(item:LocationItem,afterSave:()=>void){const overlay=document.createElement('div');overlay.className='ps-modal';overlay.innerHTML=`<div class="ps-dialog" dir="rtl"><button class="ps-close">×</button><h2>עריכת תחנת נוסעים</h2><label>שם התחנה<input data-field="name" value="${escapeHtml(item.name)}"></label><label>קישור Google Maps<input data-field="maps_url" value="${escapeHtml(item.maps_url)}"></label><label>קישור Waze<input data-field="waze_url" value="${escapeHtml(item.waze_url)}"></label><label>נקודת ציון<input data-field="coordinates" value="${escapeHtml(item.coordinates)}"></label><label>ק״מ רכבתי — לא חובה<input data-field="km" value="${escapeHtml(item.km||'')}"></label><label>הערות<textarea data-field="notes">${escapeHtml(item.notes.replace(MARKER,'').trim())}</textarea></label><div class="ps-actions"><button class="ps-cancel">ביטול</button><button class="ps-save">שמירה</button></div><p class="ps-error"></p></div>`;document.body.appendChild(overlay);const close=()=>overlay.remove();overlay.querySelector('.ps-close')?.addEventListener('click',close);overlay.querySelector('.ps-cancel')?.addEventListener('click',close);overlay.querySelector('.ps-save')?.addEventListener('click',async()=>{const value=(field:string)=>(overlay.querySelector(`[data-field="${field}"]`) as HTMLInputElement|HTMLTextAreaElement).value.trim();const error=overlay.querySelector('.ps-error') as HTMLElement;try{await api(`/locations/${item.id}`,{method:'PUT',body:JSON.stringify({...item,name:value('name'),maps_url:value('maps_url'),waze_url:value('waze_url'),coordinates:value('coordinates'),km:value('km'),notes:`${MARKER} ${value('notes')}`.trim(),allow_duplicate:false})});close();afterSave()}catch(reason){error.textContent=(reason as Error).message}})}

async function renderStations(host:HTMLElement){host.innerHTML='<div class="ps-loading">טוען תחנות נוסעים…</div>';try{const all=await api<LocationItem[]>('/locations');const order=new Map(STATIONS.map((name,index)=>[normalize(name),index]));const items=all.filter(item=>item.notes.includes(MARKER)).sort((a,b)=>(order.get(normalize(a.name))??999)-(order.get(normalize(b.name))??999));host.innerHTML=`<div class="ps-head"><div><h2>תחנות נוסעים</h2><p>${items.length} תחנות רכבת ישראל, מסודרות מדרום לצפון</p></div><input class="ps-search" placeholder="חיפוש תחנה"></div><div class="ps-grid"></div>`;const grid=host.querySelector('.ps-grid') as HTMLElement;const draw=(query='')=>{grid.innerHTML='';items.filter(item=>item.name.includes(query)).forEach(item=>{const card=document.createElement('article');card.className='ps-card';card.innerHTML=`<div><span class="ps-badge">תחנת נוסעים</span><h3>${escapeHtml(item.name)}</h3>${item.coordinates?`<small>${escapeHtml(item.coordinates)}</small>`:''}</div><div class="ps-links">${item.waze_url?`<a href="${escapeHtml(item.waze_url)}" target="_blank" rel="noreferrer">Waze</a>`:''}${item.maps_url?`<a href="${escapeHtml(item.maps_url)}" target="_blank" rel="noreferrer">Google Maps</a>`:''}<button>עריכה</button></div>`;card.querySelector('button')?.addEventListener('click',()=>openEditor(item,()=>renderStations(host)));grid.appendChild(card)})};draw();(host.querySelector('.ps-search') as HTMLInputElement).addEventListener('input',event=>draw((event.target as HTMLInputElement).value.trim()))}catch(reason){host.innerHTML=`<div class="error-box">${escapeHtml((reason as Error).message)}</div>`}}

function activate(tabs:HTMLElement,button:HTMLButtonElement){tabs.querySelectorAll('button').forEach(item=>item.classList.remove('active'));button.classList.add('active');const panel=tabs.closest('.panel') as HTMLElement|null;if(!panel)return;Array.from(panel.children).forEach(child=>{if(child!==tabs)(child as HTMLElement).style.display='none'});let host=panel.querySelector('.ps-view') as HTMLElement|null;if(!host){host=document.createElement('div');host.className='ps-view';panel.appendChild(host)}host.style.display='block';renderStations(host)}
function restore(tabs:HTMLElement){const panel=tabs.closest('.panel') as HTMLElement|null;if(!panel)return;Array.from(panel.children).forEach(child=>(child as HTMLElement).style.display='');const host=panel.querySelector('.ps-view') as HTMLElement|null;if(host)host.style.display='none'}

function installTabs(){ensureStyles();document.querySelectorAll<HTMLElement>('.tabs.three-tabs').forEach(tabs=>{if(tabs.querySelector('[data-passenger-stations]'))return;const button=document.createElement('button');button.dataset.passengerStations='true';button.textContent='תחנות נוסעים';button.addEventListener('click',()=>activate(tabs,button));tabs.querySelectorAll('button').forEach(existing=>existing.addEventListener('click',()=>restore(tabs)));tabs.insertBefore(button,tabs.children[2]||null)})}

installTabs();setInterval(()=>{installTabs();void seedStations()},2500);
