type Session = { token:string; user?:{role?:string} };
type LocationItem = { id:number; category:string; place_type:string; name:string; km:string; waze_url:string; maps_url:string; coordinates:string; notes:string };

const API=(import.meta.env.VITE_API_URL||'/api').replace(/\/$/,'');
const MARKER='[תחנת נוסעים רכבת ישראל]';
const STATIONS=[
'דימונה','באר שבע מרכז','באר שבע צפון – אוניברסיטה','להבים – רהט','קריית גת','אופקים','נתיבות','שדרות','אשקלון','קריית מלאכי – יואב','אשדוד – עד הלום','יבנה מערב','יבנה מזרח','רחובות','מזכרת בתיה','רמלה','לוד','לוד – גני אביב','באר יעקב','ראשון לציון – הראשונים','ראשון לציון – משה דיין','בת ים – קוממיות','בת ים – יוספטל','צומת חולון','חולון – וולפסון','כפר חב״ד','נתב״ג','ירושלים – יצחק נבון','ירושלים – גן החיות התנ״כי','ירושלים – מלחה','מודיעין מרכז','פאתי מודיעין','תל אביב – ההגנה','תל אביב – השלום','תל אביב – סבידור מרכז','תל אביב – אוניברסיטה','בני ברק','פתח תקווה – קריית אריה','פתח תקווה – סגולה','ראש העין צפון','כפר סבא – נורדאו','הוד השרון – סוקולוב','רעננה דרום','רעננה מערב','הרצליה','בית יהושע','נתניה – ספיר','נתניה','חדרה מערב','קיסריה – פרדס חנה','בנימינה','עתלית','חיפה – חוף הכרמל','חיפה – בת גלים','חיפה מרכז – השמונה','מרכזית המפרץ','חוצות המפרץ','קריית חיים','קריית מוצקין','עכו','אחיהוד','כרמיאל','יקנעם – כפר יהושע','מגדל העמק – כפר ברוך','עפולה','בית שאן','נהריה'
];

function session():Session|null{try{return JSON.parse(localStorage.getItem('danel_location_session')||sessionStorage.getItem('danel_location_session')||'null')}catch{return null}}
async function api<T>(path:string,options:RequestInit={}):Promise<T>{const s=session();if(!s?.token)throw new Error('נדרשת התחברות');const r=await fetch(`${API}${path}`,{...options,headers:{'Content-Type':'application/json',Authorization:`Bearer ${s.token}`,...(options.headers||{})}});if(!r.ok){let d:any={};try{d=await r.json()}catch{}throw new Error(typeof d.detail==='string'?d.detail:d.detail?.message||'שגיאה בשמירת התחנה')}return r.status===204?undefined as T:r.json()}
const norm=(v:string)=>v.replace(/[״׳'"\-–—\s]/g,'').toLowerCase();
const maps=(lat:number,lng:number)=>`https://www.google.com/maps/search/?api=1&query=${lat},${lng}`;
const waze=(lat:number,lng:number)=>`https://www.waze.com/ul?ll=${lat},${lng}&navigate=yes`;

async function geocode(name:string){const q=encodeURIComponent(`תחנת רכבת ${name}, ישראל`);const r=await fetch(`https://nominatim.openstreetmap.org/search?format=json&limit=1&countrycodes=il&q=${q}`,{headers:{'Accept-Language':'he'}});if(!r.ok)return null;const rows=await r.json();if(!rows?.[0])return null;return {lat:Number(rows[0].lat),lng:Number(rows[0].lon)};}
const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));

async function seedStations(onProgress?:(text:string)=>void){const s=session();if(s?.user?.role!=='owner')return;const all=await api<LocationItem[]>('/locations');const existing=new Set(all.filter(x=>x.notes.includes(MARKER)).map(x=>norm(x.name)));const missing=STATIONS.filter(n=>!existing.has(norm(n)));for(let i=0;i<missing.length;i++){const name=missing[i];onProgress?.(`מוסיף תחנות נוסעים: ${i+1} מתוך ${missing.length} — ${name}`);try{const point=await geocode(name);if(point){await api('/locations',{method:'POST',body:JSON.stringify({category:'reporting_point',place_type:'station',name,km:'',coordinates:`${point.lat.toFixed(6)}, ${point.lng.toFixed(6)}`,maps_url:maps(point.lat,point.lng),waze_url:waze(point.lat,point.lng),notes:MARKER,allow_duplicate:false})})}}catch(e){console.warn('Passenger station seed failed',name,e)}await sleep(1100)}onProgress?.('מאגר תחנות הנוסעים מעודכן');}

function esc(v:string){return v.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]!))}
function modal(item:LocationItem,onSaved:()=>void){const wrap=document.createElement('div');wrap.className='ps-modal';wrap.innerHTML=`<div class="ps-dialog" dir="rtl"><button class="ps-x">×</button><h2>עריכת תחנת נוסעים</h2><label>שם התחנה<input id="ps-name" value="${esc(item.name)}"></label><label>קישור Google Maps<input id="ps-maps" value="${esc(item.maps_url)}"></label><label>קישור Waze<input id="ps-waze" value="${esc(item.waze_url)}"></label><label>נקודת ציון<input id="ps-coords" value="${esc(item.coordinates)}"></label><label>ק״מ רכבתי — לא חובה<input id="ps-km" value="${esc(item.km||'')}"></label><label>הערות<textarea id="ps-notes">${esc(item.notes.replace(MARKER,'').trim())}</textarea></label><div class="ps-actions"><button class="ps-cancel">ביטול</button><button class="ps-save">שמירה</button></div><p class="ps-error"></p></div>`;document.body.appendChild(wrap);const close=()=>wrap.remove();wrap.querySelector('.ps-x')?.addEventListener('click',close);wrap.querySelector('.ps-cancel')?.addEventListener('click',close);wrap.querySelector('.ps-save')?.addEventListener('click',async()=>{const val=(id:string)=>(wrap.querySelector(id) as HTMLInputElement|HTMLTextAreaElement).value.trim();const error=wrap.querySelector('.ps-error') as HTMLElement;try{await api(`/locations/${item.id}`,{method:'PUT',body:JSON.stringify({...item,name:val('#ps-name'),maps_url:val('#ps-maps'),waze_url:val('#ps-waze'),coordinates:val('#ps-coords'),km:val('#ps-km'),notes:`${MARKER} ${val('#ps-notes')}`.trim(),allow_duplicate:false})});close();onSaved()}catch(e){error.textContent=(e as Error).message}})}

async function render(host:HTMLElement){host.innerHTML='<div class="ps-loading">טוען תחנות נוסעים…</div>';try{const all=await api<LocationItem[]>('/locations');const order=new Map(STATIONS.map((n,i)=>[norm(n),i]));const items=all.filter(x=>x.notes.includes(MARKER)).sort((a,b)=>(order.get(norm(a.name))??999)-(order.get(norm(b.name))??999));host.innerHTML=`<div class="ps-head"><div><h2>תחנות נוסעים</h2><p>${items.length} תחנות רכבת ישראל, מסודרות מדרום לצפון</p></div><input class="ps-search" placeholder="חיפוש תחנה"></div><div class="ps-grid"></div>`;const grid=host.querySelector('.ps-grid') as HTMLElement;const draw=(q='')=>{grid.innerHTML='';items.filter(x=>x.name.includes(q)).forEach(item=>{const card=document.createElement('article');card.className='ps-card';card.innerHTML=`<div><span class="ps-badge">תחנת נוסעים</span><h3>${esc(item.name)}</h3>${item.coordinates?`<small>${esc(item.coordinates)}</small>`:''}</div><div class="ps-links">${item.waze_url?`<a href="${esc(item.waze_url)}" target="_blank" rel="noreferrer">Waze</a>`:''}${item.maps_url?`<a href="${esc(item.maps_url)}" target="_blank" rel="noreferrer">Google Maps</a>`:''}<button>עריכה</button></div>`;card.querySelector('button')?.addEventListener('click',()=>modal(item,()=>render(host)));grid.appendChild(card)})};draw();(host.querySelector('.ps-search') as HTMLInputElement).addEventListener('input',e=>draw((e.target as HTMLInputElement).value.trim()))}catch(e){host.innerHTML=`<div class="error-box">${esc((e as Error).message)}</div>`}}

function style(){if(document.getElementById('ps-style'))return;const s=document.createElement('style');s.id='ps-style';s.textContent=`.ps-view{padding:22px}.ps-head{display:flex;justify-content:space-between;gap:18px;align-items:center;margin-bottom:20px}.ps-head h2{margin:0 0 5px}.ps-head p{margin:0;color:#6b7280}.ps-search{min-width:240px;border:1px solid #ccd6e5;border-radius:10px;padding:12px}.ps-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(280px,1fr));gap:14px}.ps-card{border:1px solid #dde5ef;border-radius:14px;padding:18px;background:#fff;display:flex;justify-content:space-between;gap:16px}.ps-card h3{margin:8px 0}.ps-card small{color:#6b7280}.ps-badge{font-size:12px;font-weight:800;color:#1746b8;background:#eaf0ff;padding:4px 8px;border-radius:999px}.ps-links{display:flex;flex-direction:column;gap:7px;min-width:100px}.ps-links a,.ps-links button{border:0;border-radius:8px;padding:8px 10px;text-align:center;text-decoration:none;background:#eef3ff;color:#1746b8;font-weight:700;cursor:pointer}.ps-modal{position:fixed;inset:0;background:#0008;z-index:9999;display:grid;place-items:center;padding:18px}.ps-dialog{width:min(620px,100%);max-height:90vh;overflow:auto;background:#fff;border-radius:18px;padding:24px;position:relative}.ps-dialog h2{margin-top:0}.ps-dialog label{display:grid;gap:6px;margin:12px 0;font-weight:700}.ps-dialog input,.ps-dialog textarea{border:1px solid #ccd6e5;border-radius:9px;padding:11px}.ps-dialog textarea{min-height:90px}.ps-x{position:absolute;left:16px;top:12px;border:0;background:none;font-size:28px}.ps-actions{display:flex;justify-content:flex-end;gap:10px;margin-top:18px}.ps-actions button{padding:10px 18px;border-radius:9px;border:0;font-weight:800}.ps-save{background:#1746b8;color:#fff}.ps-error{color:#b42318}.ps-loading{padding:32px;text-align:center}@media(max-width:650px){.ps-head{align-items:stretch;flex-direction:column}.ps-search{min-width:0}.ps-card{flex-direction:column}.ps-links{flex-direction:row;flex-wrap:wrap}}`;document.head.appendChild(s)}

let active=false;
function install(){style();document.querySelectorAll<HTMLElement>('.tabs.three-tabs').forEach(tabs=>{if(tabs.querySelector('[data-passenger-stations]'))return;const btn=document.createElement('button');btn.dataset.passengerStations='1';btn.textContent='תחנות נוסעים';btn.addEventListener('click',()=>{active=true;tabs.querySelectorAll('button').forEach(b=>b.classList.remove('active'));btn.classList.add('active');const panel=tabs.closest('.panel') as HTMLElement;if(!panel)return;Array.from(panel.children).forEach((c:any)=>{if(c!==tabs)c.style.display='none'});let host=panel.querySelector('.ps-view') as HTMLElement;if(!host){host=document.createElement('div');host.className='ps-view';panel.appendChild(host)}host.style.display='block';render(host)});tabs.querySelectorAll('button:not([data-passenger-stations])').forEach(b=>b.addEventListener('click',()=>{active=false;const panel=tabs.closest('.panel') as HTMLElement;panel?.querySelectorAll<HTMLElement>(':scope > *').forEach(c=>c.style.display='');const h=panel?.querySelector('.ps-view') as HTMLElement;if(h)h.style.display='none'}));tabs.insertBefore(btn,tabs.children[2]||null)});if(active){const b=document.querySelector('[data-passenger-stations]') as HTMLButtonElement;b?.click()}}

const observer=new MutationObserver(()=>install());observer.observe(document.body,{childList:true,subtree:true});install();
let seeded=false;setInterval(()=>{const s=session();if(!seeded&&s?.token&&s.user?.role==='owner'){seeded=true;seedStations(text=>console.info(text)).then(()=>{const host=document.querySelector('.ps-view') as HTMLElement;if(active&&host)render(host)}).catch(console.warn)}},2500);
